### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [dblock/danger-toc#12]
Follow https://github.com/dblock/danger-toc/blob/master/RELEASING.md.

**Comment by dblock** [comment]
@mr-dxdy this one is all yours

**Comment by mr-dxdy** [comment]
Done.  I fixed some typos in RELEASING.md. [Link](https://github.com/dblock/danger-toc/commit/656ed2d65f7571d497fba7ab517ac6dd50001aee).
